sudo: false

language: go

git:
    depth: 1
  
install: 
    - apt install hugo -y
    - go get github.com/polym/upx

script:
    - hugo

after_success:
    - upx notadd ibenchu bc123qwe
    - upx put public/   demo/
