sudo: required

language: go

go: 1.9

git:
    submodules: true
  
install: 
    - go get -v github.com/gohugoio/hugo
    - go get github.com/polym/upx

script:
    - hugo

after_success:
    - upx notadd ibenchu xxx
    - upx put public/   demo/
