sudo: required

language: go

go: 1.9

git:
    submodules: true
    

install: 
    - curl -o http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 upx

after_success:
    - upx login docs-notadds "$DOCS" "$UPYUN"
    - upx put ./*   docs/
