sudo: required

language: go

go: master

git:
    submodules: true
  
install: 
    - curl -O https://github.com/gohugoio/hugo/releases/download/v0.31/hugo_0.31_Linux-64bit.tar.gz
    - tar -zxvf hugo_0.31_Linux-64bit\ .tar.gz
    - go get github.com/polym/upx

script:
    - ./hugo

after_success:
    - upx notadd ibenchu bc123qwe
    - upx put public/   demo/
